#
# Got this from https://docs.openshift.com/container-platform/4.9/hardware_enablement/psap-special-resource-operator.html
# Doesn't work with 4.8.20 ....
#
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-special-resource-operator

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-special-resource-operator-
  name: openshift-special-resource-operator
  namespace: openshift-special-resource-operator
spec:
  targetNamespaces:
  - openshift-special-resource-operator

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: special-resource-operator
  namespace: openshift-special-resource-operator
spec:
  channel: "4.8"
  installPlanApproval: Automatic
  name: special-resource-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
