apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: sts-silicom
  namespace: sro
spec:
  namespace: sts-silicom
  # debug: true
  chart:
    name: sts-silicom
    version: 0.0.1
    repository:
      name: sts-silicom
      url: cm://sts-silicom/sts-silicom
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    imageRegistry: quay.io/silicom
    operatorImage: sts-operator:0.0.1
    driverRegistry: image-registry.openshift-image-registry.svc:5000/sts-silicom
    logLevel: 10
    nodeSelectorTerms:
      - feature.node.kubernetes.io/pci-0200_8086_1591_1374_02d0.present
      - feature.node.kubernetes.io/pci-0200_8086_1591_1374_02de.present
      - feature.node.kubernetes.io/pci-0200_8086_1591_1374_02d8.present
    runArgs:
      platform: openshift-container-platform
    buildArgs:
    - name: ICE_VERSION
      value: 1.6.4
    - name: BUILD_BASE
      value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bb5c296b4a6125f475906f457cdf2ffd35d3d70d333073a7735c2dfb29225d6d
    # oc adm release info 4.8.6 --image-for=driver-toolkit
