apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: sts-silicom
  namespace: sro
spec:
  namespace: sts-silicom-sro
  nodeSelector:
    feature.node.kubernetes.io/custom-silicom.sts.devices: "true"
  debug: true
  chart:
    name: sts-silicom
    version: 0.0.1
    repository:
      name: sts-silicom
      url: cm://sts-silicom/sts-silicom
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    driverRegistry: image-registry.openshift-image-registry.svc:5000/sts-silicom
    runArgs:
      platform: openshift-container-platform
    buildArgs:
    - name: ICE_VERSION
      value: 1.6.4
    # oc adm release info 4.8.6 --image-for=driver-toolkit
