apiVersion: sts.silicom.com/v1alpha1
kind: StsConfig
metadata:
  name: bc-1
  namespace: sts-silicom
spec:
  namespace: sts-silicom
  imageRegistry: quay.io/silicom
  nodeSelector:
    mode.sts.silicom.com/bc-1: "true"
  mode: BoundaryClock
  interfaces:
    - ethName: enp2s0f0
      synce: 1
      holdoff: 500
      mode: Slave
      ethPort: 0
    - ethName: enp2s0f1
      synce: 1
      holdoff: 500
      ethPort: 1
      mode: GrandMaster
    - ethName: enp2s0f2
      synce: 1
      holdoff: 500
      ethPort: 2
      mode: GrandMaster
