---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.driverContainer}}
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.driverContainer}}

---

apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.driverBuild}}
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.driverBuild}}
  annotations:
    specialresource.openshift.io/wait: "true"
    specialresource.openshift.io/driver-container-vendor: "sts-silicom"
    specialresource.openshift.io/kernel-affine: "true"
spec:
  nodeSelector:
    feature.node.kubernetes.io/custom-silicom.sts.devices: "true"
  resources:
    limits:
      ephemeral-storage: "10Gi"
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    configMaps:
      - configMap:
          name: ice-driver
    dockerfile: |
      ARG BUILD_BASE
      FROM $BUILD_BASE
      MAINTAINER "rmr@silicom.dk"

      ARG ICE_VERSION
      WORKDIR /build
      COPY ice.tgz .
      RUN tar xvf ice.tgz
      RUN make -C ice-$ICE_VERSION/src -j4

      FROM registry.access.redhat.com/ubi8/ubi-minimal
      ARG ICE_VERSION
      RUN microdnf install pciutils kmod procps iproute nc util-linux
      COPY --from=0 /build/ice-$ICE_VERSION/src/ice.ko /
      COPY --from=0 /build/ice-$ICE_VERSION/ddp/*.pkg /root/ice.pkg
  strategy:
    dockerStrategy:
      buildArgs:
        {{- range $arg := .Values.buildArgs }}
        - name: {{ $arg.name }}
          value: {{ $arg.value }}
        {{- end }}
        - name: BUILD_BASE
#          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:aea6d1e324558e2484bb14d6ffb8455fc752628c12118e8f33c8ae0a31990e06
          value: {{.Values.driverToolkitImage}}

  output:
    to:
      kind: DockerImage
      name: "{{.Values.driverRegistry}}/{{.Values.specialresource.metadata.name}}-{{.Values.groupName.driverContainer}}:v{{.Values.kernelFullVersion}}"
