---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
  namespace: {{.Values.specialresource.spec.namespace}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
  namespace: {{.Values.specialresource.spec.namespace}}
rules:
# - apiGroups:
#   - silicom.com
#   resources:
#   - '*'
#   - STSPtp
#   verbs:
#   - '*'
# - apiGroups:
#   - coordination.k8s.io
#   resources:
#   - leases
#   verbs:
#   - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
rules:
- apiGroups:
  - ""
  resources:
  - "nodes"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"
  - "update"
- apiGroups:
  - "apps"
  resources: 
  - "daemonsets"
  verbs:
  - "get"
# - apiGroups: [""]
#   resources: ["pods/eviction"]
#   verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
subjects:
- kind: ServiceAccount
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
  namespace: {{.Values.specialresource.spec.namespace}}
roleRef:
  kind: ClusterRole
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
  namespace: {{.Values.specialresource.spec.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
subjects:
- kind: ServiceAccount
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
  namespace: {{.Values.specialresource.spec.namespace}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}-entrypoint-gpsd
  namespace: {{.Values.specialresource.spec.namespace}}
data:
  entrypoint.sh: |
    #!/bin/bash

    # get the acm tty 
    acm_tty=`ls /sys/class/tty/ |grep ACM |tail -n 1`

    # set the line speed:
    stty -F /dev/$acm_tty ispeed 9600
    stty -F /dev/$acm_tty ispeed 9600
    echo -e -n  '\xB5\x62\x06\x02\x0A\x00\x00\x00\x00\x00\xFF\xFF\xFF\xFF\xFF\x00\x0D\xD2' > /dev/$acm_tty

    # run gpsd daemon
    echo "gpsd -n -N -D 5 /dev/$acm_tty"
    gpsd -n -N -D 5 /dev/$acm_tty &> /tmp/gpsd.log &

    nc -lk 0.0.0.0 8081

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}-entrypoint
  namespace: {{.Values.specialresource.spec.namespace}}
data:
  entrypoint.sh: |
    #!/bin/bash

    while ! nc -z 0.0.0.0 8081; do
        echo "Waiting for gpsd"
        sleep 3;
    done

    cp /etc/tsyncd/tsyncd.conf /tmp/tsyncd.conf

    let i=1
    for dev in $(lspci -d 8086:1591 | cut -d " " -f 1) ; do
        netdev=$(basename $(realpath /sys/bus/pci/devices/0000:$dev/net/*))

        sed -i "s/nicStr$i = .*$/nicStr$i = $netdev/" /tmp/tsyncd.conf
        echo "Listening on $netdev"
        let i=$i+1
    done

    if [ -e /etc/tsyncd/UC02_STS2r2_min.mfg ]
    then
      /usr/bin/plltool -l /etc/tsyncd/UC02_STS2r2_min.mfg
      /usr/bin/plltool -i
    fi

    rm -f /var/run/tsyncd.pid
    /usr/bin/tsyncd -fp /tmp/tsyncd.conf

    sleep 5

    tail -f /var/log/tsyncd.log

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}-conf
  namespace: {{.Values.specialresource.spec.namespace}}
data:
  tsyncd.conf: |
    profileID = 2
    nicStr1 = ens4
    nicStr2 = ens5
    nicStr3 = ens6
    nicStr4 = ens7
    nicStr5 = ens8
    nicStr6 = ens9
    nicStr7 = ens10
    nicStr8 = ens11
    IPCServer = 1
    domainNum = 24
    forwardable = 0
    twoStep = 0
    priority2 = 128
    srcPPS = 1
    src10MHz = 1
    synceRecClkPort = 0
    syncOption = 1
    qlEnable1 = 1
    #qlEnable2 = 1
    #qlEnable3 = 1
    #qlEnable4 = 1
    #qlEnable5 = 1
    #qlEnable6 = 1
    #qlEnable7 = 1
    #qlEnable8 = 1
    holdOff1 = 500
    #holdOff2 = 500
    #holdOff3 = 500
    #holdOff4 = 500
    #holdOff5 = 500
    #holdOff6 = 500
    #holdOff7 = 500
    #holdOff8 = 500
    synceCpu = 10
    swTimestamp = 0
    inbandMode = 1 
    dumpMode = 0
    getRawTs = 0
    countDelay = 0
    dataDelay = 0
    statDelay = 0
    aprLevel = 8
    traceModule = 23
    traceLevel = 8
    tracePtpMsg = 0
    whenWriteLog = 0
    debugAPI = 1
  tsyncd-run.cfg: |
    net_id=1591
    delay=10
    lane_map=8
    bcm_port_mask=0xff
    num_ports_10G=8
    num_ports_25G=4

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
  namespace: {{.Values.specialresource.spec.namespace}}
  annotations:
    openshift.io/scc: silicom-sts
    specialresource.openshift.io/state: "device-plugin"
    specialresource.openshift.io/wait: "true"
spec:
  selector:
    matchLabels:
      app: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
  template:
    metadata:
      # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
      # reserves resources for critical add-on pods so that they can be rescheduled after
      # a failure.  This annotation works in tandem with the toleration below.
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
    spec:
      nodeSelector:
        feature.node.kubernetes.io/usb-ff_1374_0001.present: "true"
      serviceAccount: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: {{.Values.imageRepo}}/{{.Values.siltsyncImage}}
        command: [ "/bin/entrypoint.sh" ]
        imagePullPolicy: Always
        name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}-ctr
        args:
        - --zap-log-level=10
        volumeMounts:
          - name: devfs
            mountPath: /dev
          - name: sysfs
            mountPath: /sys
          - name: tsyncd-conf
            mountPath: /etc/tsyncd
            readOnly: true
          - name: entrypoint
            mountPath: /bin/entrypoint.sh
            subPath: entrypoint.sh
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          seLinuxOptions:
            level: "s0"
      - image: {{.Values.imageRepo}}/{{.Values.siltsyncImage}}
        command: [ "/bin/entrypoint.sh" ]
        imagePullPolicy: Always
        name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}-gps
        volumeMounts:
          - name: devfs
            mountPath: /dev
          - name: sysfs
            mountPath: /sys
          - name: entrypoint-gpsd
            mountPath: /bin/entrypoint.sh
            subPath: entrypoint.sh
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          seLinuxOptions:
            level: "s0"
      volumes:
        - name: devfs
          hostPath:
            path: /dev
        - name: sysfs
          hostPath:
            path: /sys
        - name: tsyncd-conf
          configMap:
            defaultMode: 0700
            name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}-conf
        - name: entrypoint
          configMap:
            defaultMode: 0700
            name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}-entrypoint
        - name: entrypoint-gpsd
          configMap:
            defaultMode: 0700
            name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.devicePlugin}}-entrypoint-gpsd